// Next Components
import type { NextPage } from 'next'
import Head from 'next/head'

// Data
import {words, getWord} from '../words';
console.log(getWord());

// Custom Components
import Header from '../components/Header';
import GameGrid from "../components/GameGrid";
import GameKeyboard from "../components/GameKeyboard";

const Home: NextPage = () => {

  // Generate random word as answer
  // track user input letters
  // handle submit
    // loop over submitted word and



  return (
    <div className="App flex flex-col justify-between h-screen w-full max-w-md m-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
          <script src="https://cdn.tailwindcss.com"></script>
      </Head>
      <Header />
      <GameGrid />
      <GameKeyboard />
    </div>
  )
}

export default Home
