// Next/React
import React, { useState } from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'

// Data
import {words, getWord} from '../words';

// Custom Components
import Header from '../components/Header';
import GameGrid from "../components/GameGrid";
import GameKeyboard from "../components/GameKeyboard";

const Home: NextPage = () => {

  // generate answer and add to state
  const [answer, getNewAnswer] = useState(getWord());
  console.log(answer)

  // gather user inputs
  const [userWord, updateWord] = useState([]);

  const handleAddLetter = (letter) => {
    if (userWord.length < 5) {
      return updateWord([...userWord, letter])
    }
  }
  const handleDeleteLetter = () => {
    updateWord(() => {
      if (userWord.length > 0) {
        return userWord.slice(0, userWord.length-1);
      } else return;
    })
  }
  const handleSubmitWord = () => {
    const wordString = userWord.join('');
    if (words.answers.includes(wordString)) {
      console.log('you guessed a real word')
    } else {
      alert('not a word')
    }
  }


  return (
    <div className="App flex flex-col justify-between h-screen w-full max-w-md m-auto bg-black text-slate-300">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <script src="https://cdn.tailwindcss.com"></script>
      </Head>
      <Header />
      <GameGrid userWord={userWord} />
      <GameKeyboard handleAddLetter={handleAddLetter} handleDeleteLetter={handleDeleteLetter} handleSubmitWord={handleSubmitWord} />
    </div>
  )
}

export default Home
